config/routes.rb
Rails.application.routes.draw do

	root 'home#index'
	
	get "index" => "home#index"
	get "accounts/accounts" => "accounts#accounts"
	
	resources :accounts

end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/models/feature.rb
class Feature < ActiveRecord::Base
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

	def index	
		@accounts = Account.all
	end

	def show
		@account = Account.find(params[:id])
	end

	def new #displays a form
		@account = Account.new
	end

	def create #Saves and redirects
		@account = Account.new(allowed_params)
		
		if @account.save
			flash[:notice] = "Account created!"
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
		@account = Account.find(params[:id])
	end

	def editmodal
		@account = Account.find(params[:id])
	end

	def update
		@account = Account.find(params[:id])
		if @account.update_attributes(allowed_params)
			redirect_to root_path
		else
			render 'new'
		end
	end

	def destroy
		@account = Account.find(params[:id])
		@account.destroy
		flash[:notice] = "Account removed!"
		redirect_to ''
	end

	def accounts #Yes, magic has been done here!
		@account = Account.new
		@accounts = Account.all
		render :layout => false
	end

	
	private
		def allowed_params
			params.require(:account).permit(:name, :description, :number, :acc_type, :acc_class)
		end
		
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@feature = Feature.new
		#@feature = Feature.find(params[:id])
	end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/accounts/_editmodal.html.erb
<div class="modal fade" id="editmodal<%=account.id%>" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Edit <%=account.name%></h4>
      </div>
      <div class="modal-body">

		<%= form_for account do |g| %>
		
				<p><b>Account Name</b></p>
				<%= g.text_field :name, :class => 'form-control', :placeholder => "Ex: Petty Cash", :value => account.name %>
				<br />
				<p><b>Account number</b></p>
				<%= g.text_field :number, :class => 'form-control', :placeholder => "Ex: 1010", :value => account.number %>
				<br />
				<p><b>Account type</b></p>
				<div class="btn-group btn-group-justified" data-toggle="buttons">
				    <label class="btn btn-primary active">
				        <%= g.radio_button :acc_type, "Asset", :checked => true %> Asset
				    </label>
				    <label class="btn btn-primary">
				        <%= g.radio_button :acc_type, "Liability" %> Liability
				    </label>
				    <label class="btn btn-primary">
				        <%= g.radio_button :acc_type, "SHE" %> Stockholder Equity
				    </label>
				</div>
				<br />		
				<p><b>Account Class</b></p>
				<%= g.text_field :acc_class, :class => 'form-control', :placeholder => "Ex: Current Assets", :value => account.acc_class %>
				<br />
				<p><b>Account Description</b></p>
				<%= g.text_area :description, :class => 'form-control', :placeholder => "Ex: The money outside of our safe for small purchases", :value => account.description %>
				<%=link_to 'Update Account', account_path(account), method: :update %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		<%= g.submit 'Edit Account', method: :put, :class => 'btn btn-primary' %>
      </div>
      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/accounts/accounts.html.erb
<%@accounts.each do |account|%>
	<%=render 'editmodal', account: account%>
<%end%>

<head>
	<%= csrf_meta_tag %>
	<script src="../assets/tableSort.js"></script>

	<script type="text/javascript">
		  $('.selectpicker').selectpicker({
		    size: 4
		  });
		  
		  //The below is temp, delete it whenever. It helps to hide the fluff/charts
		$( "#hidestuff" ).click(function() {
			$( ".tempMark" ).toggle();
		});
	</script>




    <title>Synoptics - Chart of Accounts</title>

</head>
<body>
						  
	<div class="panel2-header">
		<button type="button" class="btn btn-default btn-sm" data-toggle="modal" href="#newacc">Add Account</button>									
		<button type="button" class="btn btn-default btn-sm" data-toggle="modal" href="#newacc">Make Adjustment</button>
		<div class="btn-group">
			<button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">Download 
				<span class="caret"></span>
			</button>
			<ul class="dropdown-menu" role="menu">
				<li><a href="#">Download PDF</a></li>
				<li><a href="#">Download Excel</a></li>
				<li><a href="#">Download CSV</a></li>
				<li class="divider"></li>
				<li><a href="#">Information</a></li>
			</ul>
		</div>	
		<button id="hidestuff" type="button" class="btn btn-default btn-sm">Hide extra</button>				  			  
	</div>
		
						  

<div class="panel2Content">
            <form style="width:250px; float:right;" class="pull-right;" action="#" method="get">
                <div class="input-group">
                    <!-- USE TWITTER TYPEAHEAD JSON WITH API TO SEARCH -->
                    <input class="form-control" id="system-search" name="q" placeholder="Search" required>
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
                    </span>
                </div>
            </form>

	<!--<p>Filter: </p>-->
	<style>
		.selected {
			border:0px;
			border-style: none;
			border-shadow:0px;
		}
	</style>
    <select id="id_select" class="selectpicker">
        <option>All</option>
        <option data-subtext="1000-1999">Assets</option>
        <option data-subtext="2000-2999">Liabilities</option>
        <option data-subtext="3000-3999">Stock Holder Equity</option>
    </select>  

	<span style="margin-bottom:5px; background-color:white;" class="glyphicon glyphicon-arrow-right"></span>							


    <select id="id_select" class="selectpicker">
        <option>All</option>
        <option>Cash</option>
        <option>Stock</option>
        <option>Short term Investments</option>
    </select>
	<br />
	
	<!--This chart is generated-->
	<% @accounts.each do |account| %>
		<script>
			$( "#<%= account.acc_type %>" ).append('<tr value="<%= account.number %>" data-toggle="modal" href="#editmodal<%=account.id%>"><td><%= account.number %></td><td><%= account.name %></td><td><%= account.acc_class %></td><td>$</td></tr>');
		</script>
	<% end %>
	
	
	<!--Assets table-->
	<table class="table table-list-search">
		<thead>
			<tr><h3 style="text-align:center;">Assets</h3></tr>
			<tr>
				<th>Account #</th>
				<th>Name</th>
				<th>Type</th>
				<th>Balance</th>
			</tr>
		</thead>
		<tbody id="Asset">
			<!--This content will be generated-->
		</tbody>
	</table>
	
	
	<!--Liabilities table-->
	<table class="table table-list-search">
		<thead>
			<tr><h3 style="text-align:center;">Liabilities</h3></tr>
			<tr>
				<th>Account #</th>
				<th>Name</th>
				<th>Type</th>
				<th>Balance</th>
			</tr>
		</thead>
		<tbody id="Liability">
			<!--This content will be generated-->
		</tbody>
	</table>
	
	
	<!--SHE table-->
	<table class="table table-list-search">
		<thead>
			<tr><h3 style="text-align:center;">Stockholders' Equity</h3></tr>
			<tr>
				<th>Account #</th>
				<th>Name</th>
				<th>Type</th>
				<th>Balance</th>
			</tr>
		</thead>
		<tbody id="SHE">
			<!--This content will be generated-->
		</tbody>
	</table>	
	<!--End of generated chart-->

</div><!--End panel2 content-->



<style>
	tr:hover{
		background-color: #34c6cd;
	}
</style>




<!-----------Modals------------->
<!--Edit Account modal is linked as a partial (see top of screen)-->
<!--The below should also be loaded as a partial-->
<div class="modal fade" id="newacc">
	<div class="modal-dialog">
		<div class="modal-content">
			<%= form_for @account do |f| %>
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				<h4 class="modal-title">New Account</h4>
			</div>
			<div class="modal-body">
		
				<p><b>Account Name</b></p>
				<%= f.text_field :name, :class => 'form-control', :placeholder => "Ex: Petty Cash" %>
				<br />
				<p><b>Account number</b></p>
				<%= f.text_field :number, :class => 'form-control', :placeholder => "Ex: 1010" %>
				<br />
				<p><b>Account type</b></p>
				<div class="btn-group btn-group-justified" data-toggle="buttons">
				    <label class="btn btn-primary active">
				        <%= f.radio_button :acc_type, "Asset", :checked => true %> Asset
				    </label>
				    <label class="btn btn-primary">
				        <%= f.radio_button :acc_type, "Liability" %> Liability
				    </label>
				    <label class="btn btn-primary">
				        <%= f.radio_button :acc_type, "SHE" %> Stockholder Equity
				    </label>
				</div>
				<br />		
				<p><b>Account Class</b></p>
				<%= f.text_field :acc_class, :class => 'form-control', :placeholder => "Ex: Current Assets" %>
				<br />
				<p><b>Account Description</b></p>
				<%= f.text_area :description, :class => 'form-control', :placeholder => "Ex: The money outside of our safe for small purchases" %>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<%= f.submit 'Create Account', :class => 'btn btn-primary' %>
			</div>
			<% end %>
		</div>
	</div>
</div>

<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>








<div style="display: none;"><!--I'm leaving this in here for later reference-->
<br /><br /><br />
<% @accounts.each do |account| %>
	<p>
		<%= account.number %><br />
		<%= account.name %><br />
		<%= account.description %><br />
		<%= account.acc_type %><br />
		<%= account.acc_class %><br />
		<%= account.balance %><br />
		
		<%= link_to 'Edit', edit_account_path(account) %><br />
		<%#= link_to 'Delete', '/accounts/:account', method: :delete %>
		<%#= link_to 'Delete Account', account, method: :destroy %>
		<%=link_to 'Delete Account', account_path(account), method: :delete %>

	</p>
<% end %>
</div>



</head>
<body>

app/views/accounts/copy-accounts.html.erb
<head>
	<script src="../assets/tableSort.js"></script>  

	<script type="text/javascript">
		  $('.selectpicker').selectpicker({
		    size: 4
		  });
	</script>


<% #render :layout => false %>


    <title>Synoptics - Chart of Accounts</title>

</head>
<body>
						  
	<div class="panel2-header">
		<button type="button" class="btn btn-default btn-sm">Add Account</button>									
	
		<div class="btn-group">
			<button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">Download 
				<span class="caret"></span>
			</button>
			<ul class="dropdown-menu" role="menu">
				<li><a href="#">Download PDF</a></li>
				<li><a href="#">Download Excel</a></li>
				<li><a href="#">Download CSV</a></li>
				<li class="divider"></li>
				<li><a href="#">Information</a></li>
			</ul>
		</div>					  			  
	</div>
		
						  

<div class="panel2Content">
            <form style="width:250px; float:right;" class="pull-right;" action="#" method="get">
                <div class="input-group">
                    <!-- USE TWITTER TYPEAHEAD JSON WITH API TO SEARCH -->
                    <input class="form-control" id="system-search" name="q" placeholder="Search" required>
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
                    </span>
                </div>
            </form>

	<!--<p>Filter: </p>-->

    <select id="id_select" class="selectpicker">
        <option>All</option>
        <option style="border:0px;" data-subtext="1000-1999">Assets</option>
        <option>Liabilities</option>
        <option>Stock Holder Equity</option>
    </select>  

	<span style="margin-bottom:5px; background-color:white;" class="glyphicon glyphicon-arrow-right"></span>							


    <select id="id_select" class="selectpicker">
        <option>All</option>
        <option>Cash</option>
        <option>Stock</option>
        <option>Short term Investments</option>
    </select>






                    <br />

    	 <table class="table table-list-search">
                    <thead>
                    	<tr><h3 style="text-align:center;">Assets</h3></tr>
                    	<tr>
                            <th>Account #</th>
                            <th>Name</th>
                            <th>Type</th>
                            <th>Balance</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1000</td>
                            <td>Cash</td>
                            <td>Current Asset</td>
                            <td>$1,000</td>
                        </tr>
                        <tr>
                            <td>1010</td>
                            <td>Petty Cash</td>
                            <td>Current Asset</td>
                            <td>$100</td>
                        </tr>
                        <tr>
                            <td>1030</td>
                            <td>Short-term Investments</td>
                            <td>Current Asset</td>
                            <td>$10,500</td>
                        </tr>
                    </tbody>
                </table>   


			
    	 <table class="table table-list-search">
                    <thead>
                    	<tr><h3 style="text-align:center;">Liabilities</h3></tr>
                        <tr>
                            <th>Account #</th>
                            <th>Name</th>
                            <th>Type</th>
                            <th>Balance</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>2000</td>
                            <td>Notes Payable</td>
                            <td>Long Term Liability</td>
                            <td>$1,000</td>
                        </tr>
                        <tr>
                            <td>2010</td>
                            <td>Bank Loans Payable</td>
                            <td>Current Asset</td>
                            <td>$12,000</td>
                        </tr>
                        <tr>
                            <td>2090</td>
                            <td>Accrued Expenses</td>
                            <td>Current Liability</td>
                            <td>$1,500</td>
                        </tr>
                    </tbody>
                </table> 


			
    	 <table class="table table-list-search">
                    <thead>
                    	<tr><h3 style="text-align:center;">Stock Holder Equity</h3></tr>
                        <tr>
                            <th>Account #</th>
                            <th>Name</th>
                            <th>Type</th>
                            <th>Balance</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>3000</td>
                            <td>Stated Capital</td>
                            <td>Equity</td>
                            <td>$0</td>
                        </tr>
                        <tr>
                            <td>3010</td>
                            <td>Capital Surplus</td>
                            <td>Equity</td>
                            <td>$100</td>
                        </tr>
                        <tr>
                            <td>3030</td>
                            <td>Retained Earnings</td>
                            <td>Equity</td>
                            <td>$0</td>
                        </tr>
                    </tbody>
                </table>          

</div>

</head>
<body>

app/views/accounts/edit.html.erb
<h2>Edit</h2>
<%= form_for @account do |f| %>

	<%= f.label :name %>
	<%= f.text_field :name %><br />

	<%= f.label :description %>
	<%= f.text_field :description %><br />
	
	<%= f.label :number %>	
	<%= f.text_field :number %><br />

	<%= f.label :acc_type %>	
	<%= f.text_field :acc_type %><br />
	
	<%= f.label :acc_class %>	
	<%= f.text_field :acc_class %><br />

	<%= f.submit 'Save new account' %>	

<% end %>

app/views/accounts/index.html.erb
<h2>Index</h2>

<% if flash[:notice] %>
<div class="alert alert-danger">
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
	<span><strong>Notice: </strong><%= flash[:notice] %></span>
</div>

<div class="alert alert-warning">
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
	<span><strong>Notice: </strong><%= flash[:notice] %></span>
</div>

<div class="alert alert-info">
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
	<span><strong>Notice: </strong><%= flash[:notice] %></span>
</div>

<div class="alert alert-success">
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
	<span><strong>Notice: </strong><%= flash[:notice] %></span>
</div>
<% end %>


<%= link_to 'Create new account', new_account_path  %>

<% @accounts.each do |account| %>
	<p>
		<%= account.number %><br />
		<%= link_to account.name, account_path(account) %><br />
		<%= account.description %><br />
		<%= account.acc_type %><br />
		<%= account.acc_class %><br />
		<%= account.balance %><br />
		
		<%= link_to 'Edit', edit_account_path(account) %><br />
		<%= link_to 'Delete', account, method: :delete %>
	</p>
<% end %>

app/views/accounts/new.html.erb
<h2>New</h2>

<%= form_for @account do |f| %>

	<%= f.label :name %>
	<%= f.text_field :name %><br />

	<%= f.label :description %>
	<%= f.text_field :description %><br />
	
	<%= f.label :number %>	
	<%= f.text_field :number %><br />

	<%= f.label :acc_type %>	
	<%= f.text_field :acc_type %><br />
	
	<%= f.label :acc_class %>	
	<%= f.text_field :acc_class %><br />

	<%= f.submit 'Save new account' %>	

<% end %>

app/views/accounts/show.html.erb
<h2>Show</h2>
<p><%= @account.name  %></p>

<%= link_to 'Back', accounts_path %>

app/views/home/index.html.erb
<%= javascript_include_tag "prototype" %><!--Do I still need this?-->

    <div class="container containerSynoptics">

		<div class="row">

		<!---------------------Begin Features List------------------->
			<div id="sidebar" class="col-sm-3">	
				<div class="span3 panel panel-success">
					  <!-- Default panel contents -->
					  <div class="panel-heading">Features</div>				
					  <!-- List group -->				  

					  <ul id="columns" class="list-group fixedList">
	

	
							  
							  <li id="feature_1" onclick="selected_feature_id = 1; select(this);" draggable="true" class="list-group-item activated column">Chart of Accounts
								<div class="listIcons pull-right">
									<span class="glyphicon glyphicon-pencil listGlyph"></span>								
									<span class="glyphicon glyphicon-remove listGlyph"></span>							
									
								</div>
							  </li>
							  
							  <li id="feature_2" onclick="selected_feature_id = 2; select(this);" draggable="true" class="list-group-item column">Balance Sheet
								<div class="listIcons pull-right">
									<span class="glyphicon glyphicon-pencil listGlyph"></span>								
									<span class="glyphicon glyphicon-remove listGlyph"></span>
								</div>
							  </li>	
							  
							  <li id="feature_3" onclick="selected_feature_id = 3; select(this);" draggable="true" class="list-group-item column">Invoices
								<div class="listIcons pull-right">
									<span class="glyphicon glyphicon-pencil listGlyph"></span>								
									<span class="glyphicon glyphicon-remove listGlyph"></span>							
								</div>
							  </li>	
							  
							  <li id="feature_4" onclick="selected_feature_id = 4; select(this);" draggable="true" class="list-group-item column">Cash Flow
								<div class="listIcons pull-right">
									<span class="glyphicon glyphicon-pencil listGlyph"></span>								
									<span class="glyphicon glyphicon-remove listGlyph"></span>								
								</div>
							  </li>	
							  						  			
							  <li id="feature_5" onclick="selected_feature_id = 5; select(this);" draggable="true" class="list-group-item column">Expenses
								<div class="listIcons pull-right">
									<span class="glyphicon glyphicon-pencil listGlyph"></span>								
									<span class="glyphicon glyphicon-remove listGlyph"></span>							
								</div>
							  </li>							  			

							  <li id="feature_6" onclick="selected_feature_id = 6; select(this);" draggable="true" class="list-group-item column">Invoices
								<div class="listIcons pull-right">
									<span class="glyphicon glyphicon-pencil listGlyph"></span>								
									<span class="glyphicon glyphicon-remove listGlyph"></span>							
								</div>
							  </li>	

							  <li id="feature_5" onclick="selected_feature_id = 5; select(this);" draggable="true" class="list-group-item column">History
								<div class="listIcons pull-right">
									<span class="glyphicon glyphicon-pencil listGlyph"></span>								
									<span class="glyphicon glyphicon-remove listGlyph"></span>							
								</div>
							  </li>	

							  <li id="feature_5" onclick="selected_feature_id = 5; select(this);" draggable="true" class="list-group-item column">Dashboard
								<div class="listIcons pull-right">
									<span class="glyphicon glyphicon-pencil listGlyph"></span>								
									<span class="glyphicon glyphicon-remove listGlyph"></span>							
								</div>
							  </li>	
					
							  <li id="feature_5" onclick="selected_feature_id = 5; select(this);" draggable="true" class="list-group-item column">Schedule Payments
								<div class="listIcons pull-right">
									<span class="glyphicon glyphicon-pencil listGlyph"></span>								
									<span class="glyphicon glyphicon-remove listGlyph"></span>							
								</div>
							  </li>						
					
							  <li id="feature_5" onclick="selected_feature_id = 5; select(this);" draggable="true" class="list-group-item column">Inventory
								<div class="listIcons pull-right">
									<span class="glyphicon glyphicon-pencil listGlyph"></span>								
									<span class="glyphicon glyphicon-remove listGlyph"></span>							
								</div>
							  </li>						

							  <li id="feature_5" onclick="selected_feature_id = 5; select(this);" draggable="true" class="list-group-item column">Time Cards
								<div class="listIcons pull-right">
									<span class="glyphicon glyphicon-pencil listGlyph"></span>								
									<span class="glyphicon glyphicon-remove listGlyph"></span>							
								</div>
							  </li>	

							  <li id="feature_5" onclick="selected_feature_id = 5; select(this);" draggable="true" class="list-group-item column">Partners
								<div class="listIcons pull-right">
									<span class="glyphicon glyphicon-pencil listGlyph"></span>								
									<span class="glyphicon glyphicon-remove listGlyph"></span>							
								</div>
							  </li>	
							  			
							  <br />		  
					  </ul>		
					<div class="panel-footer coloredFooter">
						<button type="button" class="btn btn-danger btn-sm pull-right">Remove</button>						
						<button type="button" class="btn btn-default btn-sm">More</button>
						<button type="button" class="btn btn-default btn-sm pull-right pullRightSpacing" onclick="showhide('sidebar');">Hide</button>
					</div><!--End Features Panel Footer-->								  	  
				</div>				
			</div>
	<!---------------------End Features List------------------->


	<!---------------------Begin Loaded Feature Area-----AKA:Box-2-------------->
			<div id="loadedFeatureArea" class="col-sm-9 pull-right">	
				<div class="span9 panel panel-success">
					  <!-- Default panel contents -->
					  <div id="panel2header" class="panel-heading">Dashboard</div>				
						  <div id="panelContent" class="panelAreaBigSynoptics">	    
							  <div class="panel2Content">

						  
								  	<!------Begin Flash Zone--------->
									<% if flash[:notice] %>
									<div style="margin-top:15px;" class="alert alert-success">
										<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
										<span><strong>Notice: </strong><%= flash[:notice] %></span>
									</div>
									<% end %>						  
								  	<!------End Flash Zone--------->						  
						  
								  <h3>Content Will be Going here!</h3>
								  <p>Try the 'Toggle' button, it's functional!</p>
								  <button type="button" class="btn btn-default btn-sm toggleSidebar">Toggle</button>
								  <br /><br />


								  <button type="button" class="btn btn-default btn-sm" onclick="loadCOA()">View Charts</button>
								  
								 

								  




							</div><!--End div panel2Content, this really just adds the right padding and stuff without interfering with level 2 banners-->
					  </div><!--End Div panelContent-->
					  
					<div class="panel-footer coloredFooter">		
						<button type="button" class="btn btn-default btn-sm" onclick="loadCOA()">View Dashboard</button><!--View the Dash, it's dashing!-->
						<button type="button" class="btn btn-default btn-sm toggleSidebar">Toggle</button>

					</div><!--End Features Panel Footer-->								  	  
				</div>				
			</div>
	<!---------------------End Loaded Feature Area------------------->
		
		
		
		</div><!--End div w/ class row--><!--This holds the two big panels-->


    </div><!-- /.container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>

<%=javascript_include_tag "application"%>
<%= csrf_meta_tags %>

    <title>Synoptics</title>

    <link href="../assets/bootstrap-select.css" rel="stylesheet">
    <link href="../assets/bootstrap.css" rel="stylesheet">
    <link href="../assets/Theme.css" rel="stylesheet">
    <link href="../assets/Synoptics.css" rel="stylesheet">

	
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
	<script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script><!--So that I can toggle the panel1 with pride-->

</head>
<body>





	<!---------------------Begin Navbar------------------->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="../index.html.php">Synoptics</a>
        </div>
        
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="activated"><a href="#">Home</a></li>
            <li><a class="navText" href="#about">Settings</a></li>
            <li><a href="#contact">Item 3</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
	<!---------------------End Navbar------------------->

	<%= yield %>






</body>


	<script src="../assets/bootstrap-select.js"></script>  
	<script src="../assets/bootstrap.js"></script>  
	<script src="../assets/sidebar.js"></script>  

</html>